### ISSUE TITLE
Header sizes

### ISSUE THREAD

**Issue by huachuman** [Elevict/Elevict-Snippets#2]
I would like to change the header sizes for .cm-header-1 through 6 but the css snippet I write is being overridden I'm guessing by the theme.

I would modify the theme myself but it will go away if you update the theme

**Comment by Elevict** [comment]
Were you by chance using the drop down CSS snippet with the gradient headers snippet? If you were, it was preventing headings from correctly updating and I fixed it. You can redownload the dropdown CSS snippet and see if it fixes your problem. Otherwise, please do include details about what theme and snippets you are using that is causing this problem. The more details the better :)
